"""
Script to run a simple select test and show all outputs.

This script:
1. Creates test data
2. Builds a DataFrame with column selection
3. Generates SQL and Pure code
4. Connects to the REPL and loads data
5. Executes the Pure query in the REPL
6. Shows the actual SQL generated by the REPL in debug mode
"""
import os
import csv
import tempfile
import sys
import subprocess
import time
import json
import re
sys.path.append('/home/ubuntu/repos/cloud-dataframe')
from cloud_dataframe.core.dataframe import DataFrame

def check_repl_running():
    """Check if the REPL is running."""
    repl_process = subprocess.Popen(
        ["ps", "-ef"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    output, _ = repl_process.communicate()
    if "java" not in output or "repl" not in output.lower():
        print("ERROR: REPL is not running. Please start the REPL first.")
        sys.exit(1)
    print("REPL is running.")

def send_to_repl(command, shell_id="run_repl"):
    """Send a command to the REPL."""
    print(f"Sending to REPL: {command}")
    
    try:
        subprocess.run(
            ["ps", "-ef"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True
        )
        
        subprocess.run(
            ["bash", "-c", f"echo '{command}' | java -cp @/home/ubuntu/repos/legend-engine/legend-engine-config/legend-engine-repl/legend-engine-repl-app-assembly/target/repl-app/repl-app/relational-classpath.txt @/home/ubuntu/repos/legend-engine/legend-engine-config/legend-engine-repl/legend-engine-repl-app-assembly/target/repl-app/repl-app/relational-replMainClass.txt"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
            timeout=5
        )
    except subprocess.TimeoutExpired:
        print("Command sent to REPL (timeout expected for long-running REPL)")
    except Exception as e:
        print(f"Error sending command to REPL: {e}")
    
    time.sleep(2)
    
    return "Command sent to REPL"

def main():
    """Run the simple select test and show all outputs."""
    # check_repl_running()
    
    with tempfile.TemporaryDirectory() as temp_dir:
        employee_data = [
            ['id', 'name', 'department_id', 'salary'],
            [1, 'Alice', 101, 75000],
            [2, 'Bob', 102, 85000],
            [3, 'Charlie', 101, 65000],
            [4, 'Diana', 103, 95000],
            [5, 'Eve', 102, 70000]
        ]
        
        employee_csv = os.path.join(temp_dir, 'employees.csv')
        with open(employee_csv, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerows(employee_data)
        
        print(f'Created test data at: {employee_csv}')
        
        print("\n=== Test 1: Basic Column Renaming ===")
        df = DataFrame.from_('employees', alias='employees_0')
        
        selected_df = df.select(
            lambda employees_0: (id := employees_0.id),
            lambda employees_0: (name := employees_0.name),
            lambda employees_0: (salary := employees_0.salary)
        )
        
        sql_code = selected_df.to_sql(dialect='duckdb')
        pure_code = selected_df.to_sql(dialect='pure_relation')
        
        expected_pure = "$employees->select(~[id, name, salary])->rename('id', 'id')->rename('name', 'name')->rename('salary', 'salary')"
        
        print('\n=== DataFrame Generated SQL ===')
        print(sql_code.strip())
        
        print('\n=== DataFrame Generated Pure ===')
        print(pure_code.strip())
        
        print('\n=== Expected Pure with rename() ===')
        print(expected_pure)
        
        if pure_code.strip() == expected_pure:
            print("Pure code generation validation: SUCCESS")
        else:
            print("Pure code generation validation: FAILED")
            print(f"Expected: {expected_pure}")
            print(f"Actual: {pure_code.strip()}")
        
        print("\n=== Test 2: Column Renaming with Different Names ===")
        df2 = DataFrame.from_('employees', alias='employees_0')
        
        selected_df2 = df2.select(
            lambda employees_0: (employee_id := employees_0.id),
            lambda employees_0: (employee_name := employees_0.name),
            lambda employees_0: (employee_salary := employees_0.salary)
        )
        
        sql_code2 = selected_df2.to_sql(dialect='duckdb')
        pure_code2 = selected_df2.to_sql(dialect='pure_relation')
        
        expected_pure2 = "$employees->select(~[employee_id, employee_name, employee_salary])->rename('id', 'employee_id')->rename('name', 'employee_name')->rename('salary', 'employee_salary')"
        
        print('\n=== DataFrame Generated SQL ===')
        print(sql_code2.strip())
        
        print('\n=== DataFrame Generated Pure ===')
        print(pure_code2.strip())
        
        print('\n=== Expected Pure with rename() ===')
        print(expected_pure2)
        
        if pure_code2.strip() == expected_pure2:
            print("Pure code generation validation: SUCCESS")
        else:
            print("Pure code generation validation: FAILED")
            print(f"Expected: {expected_pure2}")
            print(f"Actual: {pure_code2.strip()}")
        
        print("\n=== Skipping REPL Interaction (not available) ===")

if __name__ == '__main__':
    main()
